name: update-schemas

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  schedule:
    - cron: '00 00 * * *'

jobs:
  hamlet-schema-updater:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docs Site
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Java Setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install
        run: |
          pip install hamlet

      - name: Generate Schemas
        run: |
          rm -rf static/schema/latest/blueprint
          hamlet -i mock -p shared -p aws -p azure schema create-schemas -o static/schema/latest/blueprint
          find .  -type f -name '*-generation-contract.json' -delete

      - name: Commit Schemas into Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: publish latest hamlet schemas
