name: update-schemas

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  schedule:
    - cron: '00 00 * * *'

jobs:
  hamlet-schema-updater:
    environment: schema_update
    runs-on: ubuntu-latest

    env:
      HAMLET_ENGINE: unicycle

    steps:
      - name: Checkout Docs Site
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install
        run: |
          pip install hamlet

      - name: Generate Schemas
        run: |
          rm -r static/schema/latest/
          hamlet -i mock -p shared -p aws -p azure schema create-schemas -o static/schema/latest/

      - name: Commit Schemas into Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: publish latest hamlet schemas
